[versions]
agp = "9.4.1"
kotlin = "2.4.20"
miuix = "0.9.4"
libsu = "6.0.0"
activityCompose = "1.13.0"
room = "2.8.5"
ksp = "2.3.12"
datastore = "1.1.7"
coroutines = "1.10.2"
junit = "4.13.2"

[libraries]
miuix-ui = { module = "top.yukonga.miuix.kmp:miuix-ui", version.ref = "miuix" }
miuix-preference = { module = "top.yukonga.miuix.kmp:miuix-preference", version.ref = "miuix" }
libsu-core = { module = "com.github.topjohnwu.libsu:core", version.ref = "libsu" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
junit = { module = "junit:junit", version.ref = "junit" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
